### PR TITLE
Add support to copy local iso into host

### PR DESCRIPTION
**Pull request by df3l0p**

### CODE REVIEW

**Comment by PeterMosmans** [comment]
Great addition, thanks! I really appreciate the extension!

However, since the `local_virtualbox_iso` is added to the defaults file, this will always be true for users. IMHO it makes more sense to *not* add it to the defaults file, so that it will only be TRUE when manually added.
Could you also add this option to the `README.md` file? Thanks again!

**Comment by PeterMosmans** [comment]
Hi @df3l0p - can you take another look at the PR and my comments? Thanks!

**Comment by df3l0p** [comment]
Hey @PeterMosmans, sorry about the delay.
Here are the changes.
LMKWYT

**Comment by PeterMosmans** [comment]
Thanks again @df3l0p !

**Pull request merged**
